"""new fields in user model

Revision ID: bf6518db3c2e
Revises: 96740218eb0a
Create Date: 2018-03-20 13:55:25.622718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6518db3c2e'
down_revision = '96740218eb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_see', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_see')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
